{
  imports = [
    ./dev/nixvim
    ./dev/git
    ./dev/kitty
    ./dev/wezterm
    ./dev/starship
    ./dev/tmux
    ./dev/fish
    ./dev/direnv
    ./dev/claude-code
    ./dev/hypruse
    ./dev/opencode
    ./dev/cargo-warp
    ./desktop/noctalia
    ./desktop/hyprland
    ./apps/firefox
    ./apps/chatgpt
  ];
}
