keys:
  - &matthew age1t55px8ak0qznjp94zknxuzq7ysuu58myl9srazjytak7efspmplqetxcd6
creation_rules:
  - path_regex: secrets/secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *matthew
  - path_regex: secrets/openai_api_key.json$
    key_groups:
    - age:
      - *matthew
