keys:
  - &matthew age1t55px8ak0qznjp94zknxuzq7ysuu58myl9srazjytak7efspmplqetxcd6
  - &thinkpad age18a0zvqfr94dvv9csvwgx4mcmmgqsax8j3zvkshsa6yqw3pkp45gq8sjpw3
  - &sun age1l7gvd876qu4xlh9jak8fm2fqcud0qm3fnuyzmp9jmuml05z034fqdytrg6
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *matthew
      - *thinkpad
      - *sun
  - path_regex: secrets/openai_api_key.json$
    key_groups:
    - age:
      - *matthew
      - *thinkpad
      - *sun
