#!/usr/bin/env sh

~/.config/polybar/load_polybar &

pcid=`hostname`
thinkpadid=laptop
oorid=nuc
desktopid=sun

if [ "$pcid" = "$thinkpadid" ]; then
  setxkbmap -option caps:swapescape
  bspc monitor -d I II III IV V VI VII VIII IX X

elif [ "$pcid" = "$desktopid" ]; then
  xrandr --output DP-0 --off \
         --output DP-1 --off \
         --output HDMI-0 --off \
         --output DP-2 --primary --mode 2560x1440 --pos 0x605 --rotate normal \
         --output DP-3 --off \
         --output DP-4 --mode 2560x1440 --pos 2560x0 --rotate right \
         --output DP-5 --off
  bspc monitor DP-2 -d I II III
  bspc monitor DP-4 -d IV V 

  bspc rule -a Obsidian='^3'
  bspc rule -a firefox desktop='^4'
  bspc rule -a Slack desktop='^5'

elif [ "$pcid" = "$oorid" ]; then
  setxkbmap -option caps:swapescape
  bspc monitor DisplayPort-2 -d I II
  bspc monitor HDMI-A-1 -d III IV 
  bspc monitor DisplayPort-1 -d V VI 

  bspc rule -a Slack desktop='^1'
  bspc rule -a firefox desktop='^2'
fi

nitrogen --restore &

bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors false
bspc config border_width        3 
bspc config window_gap          2
bspc config focused_border_color \#9ECE6A
bspc config -m focused top_padding 25
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
