#!/usr/bin/env sh

~/.config/polybar/load_polybar &

pcid=`hostname`
thinkpadid=laptop
oorid=nuc
desktopid=sun

if [ "$pcid" = "$thinkpadid" ]; then
  setxkbmap -option caps:swapescape
  bspc monitor -d I II III IV V VI VII VIII IX X

elif [ "$pcid" = "$desktopid" ]; then
  xrandr --output DP-0 --off \
         --output DP-1 --off \
         --output HDMI-0 --off \
         --output DP-2 --primary --mode 2560x1440 --pos 0x602 --rotate normal \
         --output DP-3 --off \
         --output DP-4 --mode 2560x1440 --pos 2560x0 --rotate right \
         --output DP-5 --off
  bspc monitor DP-4 -d I II III
  bspc monitor DP-2 -d IV V 

  feh --bg-fill --no-xinerama ~/.config/wallpapers/6304411213_c2fc1f7e26_o.jpg

  bspc rule -a Obsidian='^3'
  bspc rule -a firefox desktop='^4'
  bspc rule -a Slack desktop='^5'

elif [ "$pcid" = "$oorid" ]; then
  notify-send "Loaded OOR Nuc"
  xrandr --output DisplayPort-2 --off \
         --output DisplayPort-3 --mode 1920x1080 --pos 4000x1322 --rotate normal \
         --output DisplayPort-4 --mode 2560x1440 --pos 0x0 --rotate right \
         --output DisplayPort-5 --off \
         --output HDMI-A-3 --off \
         --output HDMI-A-4 --mode 2560x1440 --pos 1440x287 --rotate normal
  setxkbmap -option caps:swapescape
  bspc monitor DisplayPort-4 -d I II
  bspc monitor HDMI-A-4 -d III IV 
  bspc monitor DisplayPort-3 -d V VI 

  bspc rule -a Slack desktop='^1'
  bspc rule -a firefox desktop='^2'
fi

nitrogen --restore &

bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors false
bspc config border_width        2 
bspc config window_gap          2
bspc config focused_border_color \#9ECE6A
bspc config -m focused top_padding 25
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
