#!/usr/bin/env sh

pkill polybar
~/.config/polybar/load_polybar &

bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors false
bspc config border_width        1 
bspc config window_gap          12
bspc config focused_border_color \#9ECE6A
bspc config -m focused top_padding 25
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

pcid=`hostname`
thinkpadid=laptop
oorid=nuc
desktopid=sun

if [ "$pcid" = "$thinkpadid" ]; then
  setxkbmap -option caps:swapescape
  feh --bg-fill  ~/.config/wallpapers/francesco-ungaro-qgZvBPM9Hm4-unsplash.jpg
  bspc monitor -d I II III IV V VI VII VIII IX X
  notify-send "Loaded Laptop"
elif [ "$pcid" = "$desktopid" ]; then
  xrandr --output DP-2.8 --primary --mode 2560x1440 --pos 0x620 --rotate normal \
         --output DP-2.1 --mode 2560x1440 --pos 2560x0 --rotate right \
         --output DP-0 --off \
         --output DP-1 --off \
         --output HDMI-0 --off \
         --output DP-2 --off \
         --output DP-3 --off \
         --output DP-4 --off \
         --output DP-5 --off

  feh --bg-fill --no-xinerama ~/.config/wallpapers/6304411213_c2fc1f7e26_o.jpg

  bspc wm -O DP-2.8 DP-2.1
  bspc monitor %DP-2.8 -d I II III
  bspc monitor %DP-2.1 -d IV V VI

  bspc rule -a Obsidian='^3'
  bspc rule -a firefox desktop='^4'
  bspc rule -a Slack desktop='^6'
  notify-send "Loaded Sun"
elif [ "$pcid" = "$oorid" ]; then
  xrandr --output DP-3 --off \
         --output DP-4 --mode 1920x1080 --pos 4000x1336 --rotate normal \
         --output DP-5 --mode 2560x1440 --pos 0x0 --rotate right \
         --output DP-6 --off \
         --output HDMI-4 --off \
         --output HDMI-5 --mode 2560x1440 --pos 1440x313 --rotate normal \
         --output DP-1-1 --off \
         --output HDMI-1-1 --off \
         --output HDMI-1-2 --off \
         --output DP-1-2 --off \
         --output HDMI-1-3 --off

  bspc wm -O DP-5 HDMI-5 DP-4
  bspc monitor DP-5 -d I II III
  bspc monitor HDMI-5 -d IV V VI 
  bspc monitor DP-4 -d VII VIII IX 

  feh --bg-fill --no-xinerama ~/.config/wallpapers/lukasz-szmigiel-8AdYB7M4OHY-unsplash.jpg  

  bspc rule -a Slack desktop='^1'
  bspc rule -a firefox desktop='^2'
  notify-send "Loaded OOR Nuc"
fi


