#!/usr/bin/env sh

pkill polybar
~/.config/polybar/load_polybar &

bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors false
bspc config border_width        1 
bspc config window_gap          12
bspc config focused_border_color \#9ECE6A
bspc config -m focused top_padding 25
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

pcid=`hostname`
thinkpadid=laptop
oorid=nuc
desktopid=sun

if [ "$pcid" = "$thinkpadid" ]; then
  setxkbmap -option caps:swapescape
  INTERNAL_MONITOR="eDP-1"
  EXTERNAL_MONITOR="DP-1-1-5"
  if [[ "$1" = 0 ]]; then
  if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
    bspc monitor "$EXTERNAL_MONITOR" -d 1 2 3 4 5
    bspc monitor "$INTERNAL_MONITOR" -d 6 7 8 9 10
    bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
  else
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 10
  fi
fi
  feh --bg-fill  ~/.config/wallpapers/francesco-ungaro-qgZvBPM9Hm4-unsplash.jpg
  bspc monitor -d I II III IV V VI VII VIII IX X
  notify-send "Loaded Laptop"
elif [ "$pcid" = "$desktopid" ]; then
  xrandr --output DP-2.8 --primary --mode 2560x1440 --pos 0x620 --rotate normal \
         --output DP-2.1 --mode 2560x1440 --pos 2560x0 --rotate right \
         --output DP-0 --off \
         --output DP-1 --off \
         --output HDMI-0 --off \
         --output DP-2 --off \
         --output DP-3 --off \
         --output DP-4 --off \
         --output DP-5 --off

  feh --bg-fill --no-xinerama ~/.config/wallpapers/6304411213_c2fc1f7e26_o.jpg

  bspc wm -O DP-2.8 DP-2.1
  bspc monitor %DP-2.8 -d I II III
  bspc monitor %DP-2.1 -d IV V VI

  bspc rule -a Obsidian='^3'
  bspc rule -a firefox desktop='^4'
  bspc rule -a Slack desktop='^6'
  notify-send "Loaded Sun"
elif [ "$pcid" = "$oorid" ]; then
  xrandr --output DP-3 --off \
         --output DP-4 --off \
         --output DP-5 --off \
         --output DP-6 --mode 2560x1440 --pos 4480x0 --rotate right \
         --output HDMI-4 --off \
         --output HDMI-5 --primary --mode 2560x1440 --pos 1920x560 --rotate normal \
         --output DP-1-1 --off \
         --output HDMI-1-1 --off \
         --output HDMI-1-2 --off \
         --output DP-1-2 --off \
         --output HDMI-1-3 --off  

  bspc wm -O HDMI-5 DP-6 DP-3 

  bspc monitor HDMI-5 -d I II III
  bspc monitor DP-6 -d IV V VI 

  feh --bg-fill --no-xinerama ~/.config/wallpapers/lukasz-szmigiel-8AdYB7M4OHY-unsplash.jpg  

  bspc rule -a firefox desktop='^4'
  bspc rule -a Slack desktop='^6'
  notify-send "Loaded OOR Nuc"
fi


